name 'jenkins-jnlp'
maintainer 'Leif Eriksen'
maintainer_email 'leif.eriksen.au+jenkins-jnlp-chef-github@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures jenkins-jnlp daemon'
version '0.4.29'
chef_version '>= 16.0'
source_url 'https://github.com/leriksen/jenkins-jnlp-chef'
issues_url 'https://github.com/leriksen/jenkins-jnlp-chef/issues'
